lst = [1, 555, -65, 6, 58, 0,  1, 2]
print(lst)
lst.append(9999)
print(lst)
lst.pop()
print(lst)
lst.pop(1)
print(lst)
lst.append(555)
print(lst)
lst.remove(555)
print(lst)
print(lst.count(1))
print(lst.count(0))
print(lst.index(1))
print(lst.index(1, 4))
print(lst.reverse())
print(lst)
print(lst.sort())
print(lst)
print(lst.sort(reverse=True))
print(lst)

